config/routes.rb
Ziols::Application.routes.draw do

  match "index" => "home#index"
  match "about" => "home#about"
  match "services" => "home#services"
  match "new_patients" => "home#new_patients"
  match "contact" => "home#contact"
  match "faq" => "home#faq"
  match "links" => "home#links"
  match "send_email" => "email#send_it"
  match "google_directions" => "maps#find_it"
  

  

  root :to => "home#index"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  
end

app/controllers/email_controller.rb
class EmailController < ApplicationController
  def send_it
    ZiolsMailer.contact_us(params[:email]).deliver
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def get_header
    headers = ["index", "about", "contact", "links", "services", "new_patients"]
    index = rand headers.size
    return headers[index]
  end

  def index
    @header = get_header
  end

  def about
    @header = get_header
  end

  def services
    @header = get_header
  end

  def new_patients
    @header = get_header
  end

  def contact
    @header = get_header
  end

  def links
    @header = get_header
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/email_helper.rb
module EmailHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/contact.html.erb
<section>
  <h1>contact</h1>

  <div class="mobile sidebar">
    <div class="column">
      <section>
        <h4>contact</h4>
        <table>
          <tr>
            <td>phone:</td>
            <td><a href="tel:7737631000">773 763 1000</a></td>
          </tr>
          <tr>
            <td>fax:</td>
            <td><a href="fax:7737637750">773 763 7760</a></td>
          </tr>
          <tr>
            <td>email:</td>
            <td><%= link_to "drziols@gmail.com" %></td>
          </tr>
        </table>
        <a href="http://www.facebook.com/ZiolsSmiles" target="_blank">Facebook</a>
      </section>

      <section>
        <h4>hours</h4>
        <table>
          <tr>
            <td>monday:</td>
            <td>9:00 - 4:00</td>
          </tr>
          <tr>
            <td>tuesday:</td>
            <td>10:00 - 7:00</td>
          </tr>
          <tr>
            <td>wednesday:</td>
            <td>by appointment</td>
          </tr>
          <tr>
            <td>thursday:</td>
            <td>10:00 - 7:00</td>
          </tr>
          <tr>
            <td>friday:</td>
            <td>9:00 - 4:00</td>
          </tr>
          <tr>
            <td>saturday:</td>
            <td>8:00 - 1:00</td>
          </tr>
        </table>
      </section>

      <section>
        <h4>address</h4>
        <ul>
          <li>5399 n milwaukee ave</li>
          <li>chicago, il 60630</li>
        </ul>
      </section>
    </div>

    <div class="column">
      <a href="http://maps.google.com/maps?um=1&ie=UTF-8&q=dr+gordon+j+ziols&fb=1&gl=us&hq=dr+gordon+j+ziols&hnear=Park+Ridge,+IL&cid=0,0,2998087269099188908&ei=s3ObTe6SNov2tgPdo42dBA&sa=X&oi=local_result&ct=image&resnum=4&ved=0CDMQnwIwAw" target="_blank" class="map-it"></a>
    </div>
  </div>

  <p>Should you have an emergency, please call our offices. If the emergency is during non-business hours, please call Dr. Ziols at <a href="tel:8479516166">847 951 6166</a>. Please feel free to email us at <%= link_to 'drziols@gmail.com' %>, or fax us at <a href="fax:7737637750">773 763 7760</a>.</p>

  <p>Making an appointment with Dr Ziols is easy. Either call us during business hours at <a href="tel:7737631000">773 763 1000</a>, or complete the form below. All fields are optional.</p>
</section>

<%= form_tag send_email_path, {:class => "send_email_form"} do %>
  <legend>make an appointment</legend>

  <fieldset>
    <%= label "email", "name" %>
    <%= text_field "email", "name" %>
  </fieldset>
  <fieldset>
    <%= label "email", "email" %>
    <%= text_field "email", "email" %>
  </fieldset>
  <fieldset>
    <%= label "email", "city" %>
    <%= text_field "email", "city" %>
  </fieldset>
  <fieldset>
    <%= label "email", "zip" %>
    <%= text_field "email", "zip" %>
  </fieldset>
  <fieldset>
    <%= label "email", "phone" %>
    <%= text_field "email", "phone" %>
  </fieldset>
  <fieldset>
    <%= label "email", "best time to call" %>
    <%= text_field "email", "call_time" %>
  </fieldset>

  <legend>
    preferred appointment time
  </legend>

  <div class="radio-group">
    <fieldset class="radio">
      <%= radio_button_tag "email[appointment_day]", "Weekdays" %>
      <%= label_tag "email_appointment_day_weekday", "Weekdays" %>
    </fieldset>

    <fieldset class="radio">
      <%= radio_button_tag "email[appointment_day]", "Weekends" %>
      <%= label_tag "email_appointment_day_weekend", "Weekends" %>
    </fieldset>
  </div>

  <div class="radio-group">
    <fieldset class="radio">
      <%= radio_button_tag "email[appointment_time]", "8:00 - 5:00" %>
      <%= label_tag "email_appointment_time_8:00_-_5:00", "8:00 - 5:00" %>
    </fieldset>

    <fieldset class="radio">
      <%= radio_button_tag "email[appointment_time]", "5:00 - 7:00" %>
      <%= label_tag "email_appointment_time_5:00_-_7:00", "5:00 - 7:00" %>
    </fieldset>
  </div>

  <fieldset>
    <%= label "email", "additional comments" %>
    <%= text_area "email", "comments" %>
  </fieldset>

  <fieldset>
    <%= submit_tag "Submit" %>
  </fieldset>
<%- end -%>

app/views/home/new_patients.html.erb
<section>
  <h1>new patients</h1>

  <p>Thank you for choosing us to provide your dental care. Our goal is to provide timely, comprehensive treatment to people of all ages with empathy and respect, in a relaxed and professional environment, using state of the art technology.</p>

  <p>For patients to choose a dental office appropriate to their needs there must exist a match between services sought by the patient and the services provided by the office. Our team maintains the highest standards of skill, concern and quality of care.</p>

  <p>Click on a link below to learn more.</p>
</section>

<a class="toggle" data-target="1">Your First Appointment</a>

<section id="showable-1" class="showable">
  <p>Your initial appointment will take approximately 1 hour. Please click <%= link_to "here", "files/new_patient_forms.pdf", :target => "_new" %> to download your New Patient Package. It is important that you completely fill out these forms and bring them, along with your insurance card, to your first visit. In order to best serve your needs we cannot begin the appointment without these records. Excellence in dentistry begins with a careful diagnosis and treatment plan to move us towards the goals we will establish together. During your first visit, we will perform a comprehensive examination of teeth, gums, bite, joints and soft tissue. We will utilize all cavity and disease detecting radiographs and intra-oral photographs to identify areas of concern, determine your needs and develop a lifetime plan for your oral health. We believe this in-depth examination to be the cornerstone of quality dentistry.</p>

  <p>Welcome to our practice and thank you for giving us the opportunity to serve your dental health needs.</p>

  <p><em>IMPORTANT: All patients under the age of 18 must be accompanied by a parent or guardian at the initial consultation.</em></p>
</section>

<a class="toggle" data-target="2">New Patient Forms</a>

<section id="showable-2" class="showable">
  <p>Please bring a copy of these forms to your first appointment, printed and filled out.</p>
  <p><%= link_to "download pdf", "files/new_patient_forms.pdf", :target => "_new" %></p>
</section>

<a class="toggle" data-target="3">Dental Insurance</a>

<section id="showable-3" class="showable">
  <p>We would be pleased to assist you in maximizing your insurance benefits by completing your claim forms. We accept most insurance plans. Contact us to find out if we are a participating provider on your insurance plan. Even if we are not a participating provider on your plan, most PPO plans offer out-of-network benefits. We do not accept DMO insurance or public aid</p>

  <p>Get the maximum insurance benefit allowable for your dental treatment. As an added benefit to our patients, we will work with you and your insurance company to process your claims and help you get the maximum insurance benefit allowable. Unfortunately, your dental insurance company will only pay a portion of your dental treatment. We will estimate your portion and ask you to pay that amount at the time of service.</p>

  <p>Everyone should be able to have a bright and healthy smile. Dr Ziols will find an affordable payment option that works for you. <%= link_to 'Contact our staff', contact_path %> to discuss your dental financing options.
</section>

<a class="toggle" data-target="4">Financial Policy</a>

<section id="showable-4" class="showable">
  <p>Dr Ziols welcomes patients with and without insurance. Dentistry is affordable at Dr Ziols' office. The staff will work with you to develop a treatment plan that will satisfy your needs and fit into your budget. Dr Ziols offers a variety of payment options to ensure that your dental treatment and cosmetic procedures are affordable. We realize that people have different needs in fulfilling their financial obligations, and therefore, are providing the following payments options.</p>

  <p>For your convenience, you may choose from any of the following forms of payment: Cash, Visa, Master Card, American Express, Discover, Personal Checks, Direct Debit to a personal account of your choice, and/or with third party financing through such companies as <%= link_to "CareCredit", 'http://www.carecredit.com/dentistry/whycc.html', {:target => "_new"} %>. </p>
</section>

<a class="toggle" data-target="5">Location & Parking</a>

<section id="showable-5" class="showable">
  <p>	<form class="send_email_form" action="http://maps.google.com/maps" method="get" target="_blank">
    <fieldset>
      <label for="starting_address">Enter your address:</label>
      <input type="text" name="saddr" id="starting_address"/>
    </fieldset>
    <input type="hidden" name="daddr" value="5399 n milwaukee ave chicago, il 60630"/>
    <fieldset>
      <input type="submit" value="get directions" />
    </fieldset>
    </form>
  </p>

  <p>By bus: The office is on CTA bus routes #56A and #270.<br/>
    By train: The Jefferson Park Metra station is 2 miles south of our office. Transfer to CTA bus #56A or #270.</p>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ziols' smiles</title>
  <%= stylesheet_link_tag :all %>	
  <%= javascript_include_tag "jquery", "application" %>
  <%= csrf_meta_tag %>
</head>

<body>
<div id="main">
  <header>
    <!-- <% @header ||= "about" %> -->
    <!-- <%= render :partial => "home/#{@header}" %> -->
    <div class="hero">
      <div class="logo-background"></div>
      <div class="logo"></div>
    </div>

    <div class="container">
      <nav>
        <ul>
          <li><%= link_to "home", root_path %></li>
          <li><%= link_to "about", about_path %></li>
          <li><%= link_to "services", services_path %></li>
          <li><%= link_to "new patients", new_patients_path %></li>
          <li><%= link_to "contact", contact_path %></li>
          <li><%= link_to "links", links_path %></li>
        </ul>
      </nav>
    </div>
  </header>

  <div class="content">
    <div class="container">
      <div>
        <%= yield %>
      </div>

      <div class="sidebar">
        <section>
          <h4>contact</h4>
          <table>
            <tr>
              <td>phone:</td>
              <td><a href="tel:7737631000">773 763 1000</a></td>
            </tr>
            <tr>
              <td>fax:</td>
              <td><a href="fax:7737637750">773 763 7760</a></td>
            </tr>
            <tr>
              <td>email:</td>
              <td><%= link_to "drziols@gmail.com" %></td>
            </tr>
          </table>
          <a href="http://www.facebook.com/ZiolsSmiles" target="_blank">Facebook</a>
        </section>

        <section>
          <h4>hours</h4>
          <table>
            <tr>
              <td>monday:</td>
              <td>9:00 - 4:00</td>
            </tr>
            <tr>
              <td>tuesday:</td>
              <td>10:00 - 7:00</td>
            </tr>
            <tr>
              <td>wednesday:</td>
              <td>by appointment</td>
            </tr>
            <tr>
              <td>thursday:</td>
              <td>10:00 - 7:00</td>
            </tr>
            <tr>
              <td>friday:</td>
              <td>9:00 - 4:00</td>
            </tr>
            <tr>
              <td>saturday:</td>
              <td>8:00 - 1:00</td>
            </tr>
          </table>
        </section>

        <section>
          <h4>address</h4>
          <ul>
            <li>5399 n milwaukee ave</li>
            <li>chicago, il 60630</li>
          </ul>
          <a href="http://maps.google.com/maps?um=1&ie=UTF-8&q=dr+gordon+j+ziols&fb=1&gl=us&hq=dr+gordon+j+ziols&hnear=Park+Ridge,+IL&cid=0,0,2998087269099188908&ei=s3ObTe6SNov2tgPdo42dBA&sa=X&oi=local_result&ct=image&resnum=4&ved=0CDMQnwIwAw" target="_blank" class="map-it"></a>
        </section>
      </div>
    </div>
  </div>

  <footer>
    <div class="container">
      <p>&copy; 2015 Gordon J Ziols, DDS</p>
      <small>designed by <%= link_to 'nick meccia', 'http://nickmeccia.com', {:target => "_new"}%> </small>
    </div>
  </footer>
</div>
	
</body>
</html>

app/views/maps/find_it.html.erb
class MapFinder
  default :from => "gordonjziols@gmail.com"
  
  def contact_us(email)
    @email = email
    mail({:to => "drziols@gmail.com", :subject => "Mail from #{email[:name]}"})
  end
end